"use server";

import { OpenRouter } from "@openrouter/sdk";
import cloudinary from "cloudinary";
import fs from "fs/promises";
import path from "path";
import connectToDB from "@/config/db";
import { getServerSession } from "next-auth";
import GhibliImage from "@/models/GhibliImage.model";

cloudinary.v2.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const openRouter = new OpenRouter({
  apiKey: process.env.OPENROUTER_API_KEY,
});

export default async function convertToGhibli(
  imageUrl,
  prompt = "Transform this image into Studio Ghibli anime style with dreamy watercolor textures, soft tones, and cinematic atmosphere."
) {
  try {
    await connectToDB();
    console.log(`🎨 Starting Ghibli conversion via OpenRouter: ${imageUrl}`);

    // 🧠 Convert remote image to base64
    const res = await fetch(imageUrl);
    const buffer = await res.arrayBuffer();
    const base64Image = Buffer.from(buffer).toString("base64");
    const dataUri = `data:image/png;base64,${base64Image}`;

    // ✅ Proper message structure
    const result = await openRouter.chat.send({
      model: "black-forest-labs/FLUX.1-schnell", // use dreamshaper-8-lcm for anime
      messages: [
        {
          role: "user",
          content: [
            { type: "text", text: `${prompt}, Studio Ghibli anime style, soft pastel lighting, gentle detail.` },
            { type: "image_url", image_url: dataUri },
          ],
        },
      ],
      stream: false,
    });

    // ✅ Extract the returned image
    const message = result?.choices?.[0]?.message;
    const generatedImage = message?.content?.find((c) => c.type === "image_url")?.image_url;

    if (!generatedImage) {
      console.error("⚠️ No image returned:", JSON.stringify(result, null, 2));
      throw new Error("No image generated by OpenRouter model.");
    }

    console.log("✅ Received Ghibli image from OpenRouter.");

    // 💾 Decode base64 to buffer
    const base64Data = generatedImage.replace(/^data:image\/\w+;base64,/, "");
    const genBuffer = Buffer.from(base64Data, "base64");

    // 💾 Save to temp file
    const tmpDir = path.join(process.cwd(), "tmp");
    await fs.mkdir(tmpDir, { recursive: true });
    const tmpFile = path.join(tmpDir, `ghibli_${Date.now()}.jpg`);
    await fs.writeFile(tmpFile, genBuffer);

    // ☁️ Upload to Cloudinary
    const upload = await cloudinary.v2.uploader.upload(tmpFile, {
      folder: "zemini/ghibli",
      format: "jpg",
      resource_type: "image",
    });

    await fs.unlink(tmpFile);

    // 💾 Save to MongoDB
    const session = await getServerSession();
    const userEmail = session?.user?.email || "guest";
    const newImage = await GhibliImage.create({
      userEmail,
      imageUrl: upload.secure_url,
      prompt,
    });

    console.log("✅ Uploaded & saved successfully.");

    return {
      status: "success",
      ghibliUrl: upload.secure_url,
      message: "Image converted to Ghibli style via OpenRouter 🎨",
      data: JSON.parse(JSON.stringify(newImage)),
    };
  } catch (error) {
    console.error("❌ Ghibli conversion failed:", error);
    return {
      status: "failed",
      message: error.message || "Something went wrong during OpenRouter conversion.",
    };
  }
}
