"use server";

import { GoogleGenerativeAI } from "@google/generative-ai";
import cloudinary from "cloudinary";
import fs from "fs/promises";
import path from "path";
import connectToDB from "@/config/db";
import { getServerSession } from "next-auth";
import GhibliImage from "@/models/GhibliImage.model";

cloudinary.v2.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

export default async function convertToGhibli(
  imageUrl,
  prompt = "Transform this image into Studio Ghibli anime style with dreamy watercolor textures, soft tones, and cinematic atmosphere."
) {
  try {
    await connectToDB();
    console.log(`Starting Ghibli conversion via Gemini: ${imageUrl}`);

    const res = await fetch(imageUrl);
    const buffer = await res.arrayBuffer();
    const base64Image = Buffer.from(buffer).toString("base64");

    const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash-exp" });

    const result = await model.generateContent({
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `${prompt}, Studio Ghibli anime style, soft pastel lighting, gentle detail.`,
            },
            {
              inlineData: {
                mimeType: "image/jpeg",
                data: base64Image,
              },
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 1,
        topP: 0.95,
        topK: 40,
        maxOutputTokens: 8192,
        responseMimeType: "image/jpeg",
      },
    });

    const imageData = result.response.candidates[0].content.parts[0].inlineData;

    if (!imageData || !imageData.data) {
      throw new Error("No image generated by Gemini model.");
    }

    console.log("Received Ghibli image from Gemini.");

    const genBuffer = Buffer.from(imageData.data, "base64");

    const tmpDir = path.join(process.cwd(), "tmp");
    await fs.mkdir(tmpDir, { recursive: true });
    const tmpFile = path.join(tmpDir, `ghibli_${Date.now()}.jpg`);
    await fs.writeFile(tmpFile, genBuffer);

    const upload = await cloudinary.v2.uploader.upload(tmpFile, {
      folder: "zemini/ghibli",
      format: "jpg",
      resource_type: "image",
    });

    await fs.unlink(tmpFile);

    const session = await getServerSession();
    const userEmail = session?.user?.email || "guest";
    const newImage = await GhibliImage.create({
      userEmail,
      originalUrl: imageUrl,
      ghibliUrl: upload.secure_url,
      prompt,
    });

    console.log("Uploaded & saved successfully.");

    return {
      status: "success",
      ghibliUrl: upload.secure_url,
      message: "Image converted to Ghibli style",
      data: JSON.parse(JSON.stringify(newImage)),
    };
  } catch (error) {
    console.error("Ghibli conversion failed:", error);
    return {
      status: "failed",
      message: error.message || "Something went wrong during Ghibli conversion.",
    };
  }
}
